steps:
  # Build da imagem Docker
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-f', 'deploy/Dockerfile', '-t', 'gcr.io/$PROJECT_ID/notas-do-dia', '.']
  
  # Push da imagem para Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/notas-do-dia']
  
  # Deploy no Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'notas-do-dia'
      - '--image'
      - 'gcr.io/$PROJECT_ID/notas-do-dia'
      - '--region'
      - 'asia-south1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--memory'
      - '4Gi'
      - '--cpu'
      - '2'
      - '--timeout'
      - '3600'
      - '--max-instances'
      - '1'
      - '--update-env-vars'
      - 'TIMEZONE=Asia/Kolkata'

images:
  - 'gcr.io/$PROJECT_ID/notas-do-dia'

timeout: '1200s'

